settings:
  # Decides if pvp should be enabled or disabled by default
  pvp_enabled_by_default: false

  # Prevents dumping lava and pufferfish bucket, placing wither roses and lighting blocks on fire near players with pvp off
  lava_and_fire_stopper:
    enabled: true
    radius: 2.5

  # Disables channeling (trident enchant) lightning strike
  # You may want to keep it disabled because players with pvp off can use it to attack players with pvp on
  channeling_enchant_disabled: false

  # Time (in seconds) to keep player in combat
  combat_time: 25

  # Kill the player if they log out during combat
  punish_for_combat_logout:
    enabled: true
    announce: true
    message: "&f%player% logged out while in combat. What a loser."

  # Time (in seconds) to keep player data in memory when players goes offline.
  # This is used for checking if offline players pvp state.
  # Adjust only if you know what you're doing. NEVER set to less than 6.
  cache_time: 30

messages:
  pvp_enabled: "&cYou enabled PvP!"
  pvp_disabled: "&cYou disabled PvP!"
  cannot_attack_victim: "&cYou can't attack players that have PvP turned off!"
  cannot_attack_attacker: "&cYou can't attack players while you have PvP turned off!"
  cannot_attack_pets_victim: "&cYou can't attack pets of players that have PvP turned off"
  cannot_attack_pets_attacker: "&cYou can't attack pets while you have PvP turned off"
  no_permission: "&cYou don't have permission to use that."
  no_such_command: "&cNo such command."
  pvp_enabled_others: "&cYou've enabled %player%'s PvP."
  pvp_disabled_others: "&cYou've disabled %player%'s PvP."
  entering_combat: "&cEntering combat"
  leaving_combat: "&cLeaving combat"
  cant_do_that_during_combat: "&cYou can't do that while in combat!"
