name: PreventStabby
version: ${project.version}
main: me.youhavetrouble.preventstabby.PreventStabby
authors: [YouHaveTrouble]
api-version: 1.13
description: Stop people from getting stabbed!
soft-depend:
  - WorldGuard
  - PlaceholderAPI
commands:
  preventstabby:
    permission: preventstabby.command
    aliases:
      - pvp
permissions:
  preventstabby.combatcommandblock.bypass:
    default: op
    description: Allows to bypass combat command blocker
  preventstabby.combatteleportblock.bypass:
    default: op
    description: Allows to bypass combat teleport blocker
  preventstabby.command:
    default: true
    description: Allows usage of /pvp command
  preventstabby.command.toggle:
    default: true
    description: Allows usage of /pvp <toggle/enable/disable> command
  preventstabby.command.toggle.others:
    default: op
    description: Allows usage of /pvp <toggle/enable/disable> <player> command
  preventstabby.command.toggle.global:
    default: op
    description: Allows usage of /pvp override <enabled/disabled/none> command
  preventstabby.command.reload:
    default: op
    description: Allows usage of /pvp reload command