name: TogglePvP
version: ${project.version}
main: eu.endermite.togglepvp.PreventStabby
authors: [YouHaveTrouble]
api-version: 1.13
description: Stop people from getting stabbed!
commands:
  preventstabby:
    aliases:
      - pvp
permissions:
  toglepvp.combatcommandblock.bypass:
    default: op
    description: Allows to bypass combat command blocker
  toglepvp.combatteleportblock.bypass:
    default: op
    description: Allows to bypass combat teleport blocker
  togglepvp.command:
    default: true
    description: Allows usage of /pvp command
  togglepvp.command.toggle:
    default: true
    description: Allows usage of /pvp <toggle/enable/disable> command
  togglepvp.command.toggle.others:
    default: op
    description: Allows usage of /pvp <toggle/enable/disable> <player> command
  togglepvp.command.reload:
    default: op
    description: Allows usage of /pvp reload command