name: TogglePvP
version: ${project.version}
main: eu.endermite.togglepvp.TogglePvP
authors: [YouHaveTrouble]
api-version: 1.13
description: PvP toggle plugin
commands:
  pvp:
    usage: /pvp [args]
permissions:
  togglepvp.command:
    default: true
    description: Allows usage of /pvp command
  togglepvp.command.toggle:
    default: true
    description: Allows usage of /pvp <toggle/enable/disable> command
  togglepvp.command.toggle.others:
    default: op
    description: Allows usage of /pvp <toggle/enable/disable> <player> command
  togglepvp.command.reload:
    default: op
    description: Allows usage of /pvp reload command